name: Build and Deploy to ECR

on:
  push:
    branches:
      - main
    paths:
      - 'tarot-front/**' # tarot-front 폴더 내의 변경사항에 대해서만 트리거됩니다.

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ap-northeast-2 # AWS 리전 설정
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push Docker image to ECR
        run: |
          ECR_REGISTRY=${{ secrets.AWS_ECR_REGISTRY }} # Use the secret value as ECR_REGISTRY
          docker build -t ${ECR_REGISTRY}/tarotmate-frontend:latest -f tarot-front/Dockerfile tarot-front/
          docker push ${ECR_REGISTRY}/tarotmate-frontend:latest
        env:
          AWS_REGION: ap-northeast-2



