name: Build and Deploy to ECR

on:
  push:
    branches:
      - main
    paths:
      - 'tarot-front/**' # tarot-front 폴더 내의 변경사항에 대해서만 트리거됩니다.

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ap-northeast-2 # AWS 리전 설정
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        run: |
          docker build -t ${{ steps.login-ecr.outputs.registry }}/tarotmate-frontend:latest -f tarot-front/Dockerfile tarot-front/
          docker push ${{ steps.login-ecr.outputs.registry }}/tarotmate-frontend:latest
